version: '3.7'
services:
    app:
        container_name: drmobile-hl7-app
        environment:
           NODE_ENV: production
           REACT_APP_API_HL7_URL: http://localhost:8080/
        image: drmobile/drmobile.hl7.app  
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3001:3000'